# Tips on Analysis

#### Think about your analytical goals

Throughout this guide, I have tried to explicitly state the goals of each analysis. This helps inform us on how to approach the analysis of an experiment. It can be difficult, especially for new scientists-in-training (i.e. graduate students), to understand what it is they want to estimate. You may have been handed a data set you had no role in generating and told to "analyze this" with no additional context. Or perhaps you may have conducted a large study that has some overall goals that are lofty, yet vague. 

It can helpful to think about the exact results you are hoping to get. What does this look like exactly? Do you want to estimate the changes in plant diversity as the result of a herbicide spraying program? Do you want to find out if a fertilizer treatment changed protein content in a crop and by how much? Do you want to know about changes in human diet due to an intervention? What are quantifiable difference that you and/or experts in your domain would find meaningful? 

Consider what the results would look like on the best case scenario when your wildest dreams come true and null results, when you find out that your treatment or invention had no effect. 

By "consider", I mean: imagine the final plot or table, or summary sentence you want to present, either in a peer-reviewed manuscript, or some output for stakeholders. From this, you work backwards to determine the analytical approach needed to arrive at that final output. Or you may determine that your data are unsuitable to generate the desired output, in which case, it's best to determine that as soon as possible. 

By "consider", I also mean: imagine exactly what the spreadsheet of results would say - what columns are present and what data are in the cells. If you are planning an experiment, this can help ensure you plan it properly to actually test whatever it is you want to evaluate. If the experiment is done, this enables you to evaluate if you have the information present to test your hypothesis. 

By taking the time to reflect on what it is you exactly want to analyse, this can save time and prevent you from doing unneeded analyses that don't serve this final goal. There is rarely (never?) one way to analyse an experiment or a data set, so use your limited time wisely and focus on what matters. 

#### Some reflections on p-values

> Informally, a p-value is the probability under a specified statistical model that a statistical summary of the data (e.g., the sample mean difference between two compared groups) would be equal to or more extreme than its observed value.
> -American Statistical Association

The great majority of researched are deeply interested in p-values. This is not a bad thing per se, but sometimes the focus is so strong it comes at the expense of other valuable pieces of information, like treatment estimates! 

The American Statistics Association [recommends](https://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1154108#.ZF_Y33bMLW-) that **"Scientific conclusions and business or policy decisions should not be based only on whether a p-value passes a specific threshold."** That articles also contain explanations regarding what p-values are telling us and how to avoid committing analytical errors and/or misinterpreting p-values. If you have time to read the full article, it will benefit your research! 

The main problematic behavior I see is researchers using p-values as the sole criteria on whether to present results: "We wanted to test if x, y and z had an effect. We ran some model and found that that only x had a significant effect, and those results indicate..." (results with a p-value < 0.05 are ignored). 

A better option would be to discuss the the results of the analysis and how they addressed the research questions: how did the dependent variable change (or not change) as a result of the treatments/interventions/independent variables? What are the parameters or treatment predictions and what do they tell us with regard to the research goals? And to bolster those estimates, what are the confidence intervals on those estimates? What are the p-values for the statistical tests? P-values can support the results and conclusions, but the main results desired by a researcher are usually the estimates themselves - so lead with that! 

#### Data cleaning

This has and will continue to occupy the majority of researcher's time when conducting an analysis. Truly, I am sorry for this. But, please know it is not you, it is the nature of data. I have written extensively about this elsewhere, but please prepare yourself to spend time cleaning and preparing your data for analysis. This will take way longer than the actual analysis! It is needed to ensure you can actually get correct results in an analysis, and hence worthy of the time invested. 


