# Additional Resources

If you have read through this guide, you can see how flexible LMMs are for addressing a broad array of analytical scenarios and in particular, are advantageous when there is unbalanced data due to missing data, unequal replication or due to the experimental design itself. However, LMMs can be easily misspecified when you are a new LMM user, so it helps to have a deeper understanding of how they work. Below are some resources than can help expand your understanding. 

## Further Reading on Mixed Models

* [UCLA Short Guide](https://stats.oarc.ucla.edu/other/mult-pkg/introduction-to-linear-mixed-models/){.external target="_blank"}

* [lme4 vignette for fitting linear mixed models](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf){.external target="_blank"} 

* [*Mixed-Effects Models in S and S-PLUS*](https://link.springer.com/book/10.1007/b98882){.external target="_blank"} *thee book* for **nlme**, by José C. Pinheiro and Douglas M. Bates (2000). We used this book extensively for developing this guide. Sadly, it's out of print,  and we could not find a free copy online. However, there are affordable used copies available; some school libraries also carry this. 

* [Data Analysis Using Regression and Multilevel/Hierarchical Models](https://www.cambridge.org/highereducation/books/data-analysis-using-regression-and-multilevel-hierarchical-models/32A29531C7FD730C3A68951A17C9D983#overview){.external target="_blank"} by Andrew Gelman and Jennifer Hill (2006). Good general introduction with a major focus on Bayesian models. [Free PDF](https://github.com/tmastny/Data-Analysis-Using-Regression-and-Multilevel-Hierarchical-Models)

* [*Mixed Effects Models and Extensions in Ecology with R*](https://link.springer.com/book/10.1007/978-0-387-87458-6){.external target="_blank"} by Alain F. Zuur, Elena N. Ieno, Neil Walker, Anatoly A. Saveliev, and Graham M. Smith (2009). 

* [*ANOVA and Mixed Models*](https://www.taylorfrancis.com/books/mono/10.1201/9781003146216/anova-mixed-models-lukas-meier){.external target="_blank"} by Lukas Meier (2022). 

## Other Related Programming Resources

If you can get stuck (and you will), the following resources may be helful for resolving your problem(s): 

* [Mixed Model CRAN Task View](https://mirror.oit.ncsu.edu/cran/web/views/MixedModels.html){.external target="_blank"} a curated list of R packages relevant to mixed modelling. This is a great place to start if you're looking for specialized modeling functionality. 

* [R-SIG-mixed-models](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models){.external target="_blank"} mailing list for help and discussion of mixed-model-related questions, course announcements, etc. 

* [Easy Stats](https://easystats.github.io/easystats/){.external target="_blank"} a collection of R packages to assist in statistical modelling with a major focus on linear models. 


