# Introduction

```{r, echo=FALSE}
library(see); library(patchwork); library(quarto)
```


This guide is focused on frequentist implementations of mixed models in R, covering different scenarios common in the agricultural and life sciences.

This is not intended to be a guide to the theory of mixed models, it is focused on implementations of models only. We do provide a [short introduction to mixed models](background.qmd). UCLA provides a [longer more comprehensive introduction](https://stats.oarc.ucla.edu/other/mult-pkg/introduction-to-linear-mixed-models/). 

## Terms

Please read this section and refer back to if when you forget what these terms mean.

| Term              | Definition                                                                                                                                                                                                                                                                    |
|:------------------|:----------------------------------------------------|
| Random effect     | An independent variable where the levels being estimated compose a random sample from a population whose variance will be estimated                                                                                                                                           |
| Fixed effect      | An independent variable with specific, predefined levels to estimate                                                                                                                                                                                                          |
| Experimental unit | The smallest unit being used for analysis. This could be an animal, a field plot, a person, a meat or muscle sample. The unit may be assessed multiple times or through multiple point in time. When the analysis is all said and done, the predictions occur at this level. |

: Terms definitions {#tbl-terms}

## Packages

### Table of required packages for modelling

| Package            |   Purpose                               |
|:----------------------------------|:--------------------------------------------|
| [lme4](https://CRAN.R-project.org/package=lme4)  [@lme4]      | main package for linear mixed models                                              |
| [lmerTest](https://cran.r-project.org/web/packages/lmerTest/index.html) [@lmertest]  | for computing p-values when using lme4                                            |
| [nlme](https://CRAN.R-project.org/package=nlme) [@nlme; @nlme_book]       | main package for linear mixed models and part of 'base R'                                             |
| [emmeans](https://rvlenth.github.io/emmeans/) [@emmeans]    | for estimating fixed effects, their confidence intervals and conducting contrasts |
| [broom.mixed](https://CRAN.R-project.org/package=broom.mixed) [@broom_mix]  | package for presenting the model summary output into a tidy workflow.             |
| [DHARMa](https://CRAN.R-project.org/package=DHARMa) [@dharma]     | for evaluating residuals (error terms) in generalized linear models               |
| [performance](https://easystats.github.io/performance/) [@performance]  | For creating diagnostic plots or to compute fit measures                          |

: Table of required packages {#tbl-req_pkg}

### Optional packages

|                  |                             |
|:-----------------|:----------------------------|
| **Package Name** | **Function**                |
| [here](https://here.r-lib.org/)             | For setting work directory  |
| [ggplot](https://ggplot2.tidyverse.org/)           | plotting                    |
| [desplot](https://kwstat.github.io/desplot/)          | plotting                    |
| [agridat](https://kwstat.github.io/agridat/)         | to download example dataset |
| [agricolae](https://CRAN.R-project.org/package=agricolae)      | to download example dataset |

: Table of optional packages {#tbl-opt_pkg}

This entire guide will use the [here](https://here.r-lib.org/) package for loading data. If you can load your data fine without this package, please carry on. 'here' is certainly not required for running mixed models.
