---
title: "Pre-model prep steps"
---

The following provides a brief introduction to the steps involved in data analysis using linear mixed models and some thoughts on data quality and data interpretation. 

## Loading data 

In this tutorial, we have used data sets mainly from the **agricolae**, **agridat** or from our previous records. 


## Data integrity checks 

The first thing is to make sure the data is what we expect. Here are the steps to verify our data:

1.  make sure data are the expected data type
2.  check the extent of missing data
3.  inspect the independent variables and make sure the expected levels are present in the data
4.  inspect the dependent variable to ensure its distribution is following expectations




This step involves verifying 

the structure of data variables, 


- check balance of independent variables 

The purpose of this step is to verify that all treatments have equal number of reps/ observations at each treatment level.


check missing values in the dataset:

It's important to verify the extent of missing values in the dataset. So 


check distribution of the response variable



## Model building

## Model Assumptions

## Inference