---
title: Troubleshooting
execute: 
  eval: false
editor: 
  markdown: 
    wrap: sentence
---

In this tutorial, we have demonstrated how to use linear mixed models for different experiment designs using examples we have already tested and know work. However, it is likely that you will eventually have issues in fitting mixed models in R. This section discusses common issues and errors that might come up when implementing mixed models.

## Common errors we encounter

1. Singular fit error 

`boundary (singular) fit: see ?isSingular`.

This error occurs because one of the variance component is approximately zero. If a model is "singular", this means that some dimensions of the variance-covariance matrix have been estimated as nearly zero or as close to zero as your computer's precision will allow. 

There is no single solution for this problem. One option is to remove the block effect or include it as a fixed effects and re-analyze the experiment. If there are no other random effects in the model, you can use the function `gls()` in **nlme** that uses generalized least squares for model fit and allows for correlated and unequal variances. 

[[need info on the drawbacks of leaving block out]]

search for `?lmercontrol` (Julia: why?????)

1.  Model failed to converge. There are several different error messsages for non-convergence, depending on what happened:

```convergence error code = 1 message = iteration limit reached without convergence (10)```


```Hessian that is not positive definite```

There are several causes for lack of convergence. Model fitting is an iterative process where in each interation, the latest estimates are compared to the estimates from the previous iteration. When there difference becomes sufficiently small, modelling packages declare that convergence criteria were met. There are several reasons why a model may not converge: (1) it needed more iterations, (2) the model does not fit the data well, (3) the software did not have a decent starting point for this model and data; among other plausible explainations.

Running this is an R console will bring up a useful help file with details on how to address convergence issues.

```
?convergence
```

### Other Tools

Troubleshooting LMM model failures is difficult. One thing that helps is to browse through your data and make sure it looks like what you expect, and that your expectations of the variables are how R seem them as well. 



Having an understanding of the moving parts of **lme4** and how they each contribute to model fit can help. A help ful **lme4** control structures for model fitting can be accessed via `
?lmerControl`. 

Posit (née RStudio) has published a [rather useful guide](https://rstudio-pubs-static.s3.amazonaws.com/33653_57fc7b8e5d484c909b615d8633c01d51.html) for advanced troubleshooting of convergence issues in **lme4**. Phillip Alday wrote a [detailed tutorial](https://rpubs.com/palday/lme4-singular-convergence) on **lme4** convergence warnings. 

