---
title: Design Matters
---

```{r, include=FALSE, echo=FALSE}
source(here::here("settings.r"))

par(mar=c(5.1, 6, 4.1, 2.1))
```

What is the data generating process? 

This is focused on experiments or trials. 

Generalized linear nixed models provide a generalized context  require:

  1. a linear predictor
  2. A distribution for the random effects
  3. A distribution for the dependent variable
  4. A link function to transform the dependent variable 
  
Items 2 through 4 are assumed constant for this guide: the random effects and dependent variable are both assumed normal, and hence the identity link function, specifying no transformation, is used. 

Errors in analysis due to incomplete understanding of the data generating process.

How do we translate an experiment into a linear model?

We need to outline the plan of what units received what treatment(s) and in what order? 

#### Step 1

Determine the smallest unit that received a treatment combination. This can be a spatial units of land (e.g. a plot), a person, an animal, part of an animal carcass, a single water sample, a soil composite for a specific depth, among many other things. This is not the same as smallest unit being measured; it is the smallest unit subject to a single combination of treatments. This is the *experimental unit*.

#### Step 2


Identify the factors or treatment. 



