on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: install linux dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install --fix-missing -y --no-install-recommends build-essential libcurl4-openssl-dev 

      - name: set up R
        uses: r-lib/actions/setup-r@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          r-version: '4.4.1'
          
      - name: fix quarto set-up issues
        run: quarto install tinytex
      
      - name: manual installtion of 'digest'
        run: |
          R -e "install.packages('digest', repos='http://cran.us.r-project.org')"
      
      - name: clear renv cache
        run: sudo rm -rf ~/.cache/R/renv
      
      - name: set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 0
          

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ENV }}
